name: Deploy para Localweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 191.252.83.224
          username: marcenario2
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            README.md
